export enum RoleName {
  OWNER = 'OWNER',
  PROPERTY_MANAGER = 'PROPERTY_MANAGER',
  ACCOUNTANT = 'ACCOUNTANT',
  SECURITY_GUARD = 'SECURITY_GUARD',
  MAINTENANCE_STAFF = 'MAINTENANCE_STAFF',
  TENANT = 'TENANT',
}
