debug: false
server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: commerce-auth-service
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  datasource:
    url: jdbc:mysql://host.docker.internal:3306/commerce_auth
    username: commerce_dev
    password: Bnroll@2003

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.bnroll: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: 6d8b4d5f1c8a9e73b2f4d1a7c9e8f6b5a1d3e7f9c2b4a6d8e1f3c5b7a9d2e4f6
  access-token:
    expiration: 300000

  refresh-token:
    expiration: 172800000    # 1day

  password-reset-token:
    expiration: 900000          # 15 minutes


springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
password:
  token:
    expiration: 300000


services:
  property:
    base-url: http://host.docker.internal:8082/property

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: billing-service
